#!/usr/bin/env bash

# Назначить максимальное количество файловых потоков
ulimit -n 50000

ARGS="--conf-dir=/etc/nimble --log-dir=/var/log/nimble --pidfile=/var/run/nimble/nimble.pid"

# Запустить service от имени nimble user
exec /usr/bin/nimble $ARGS
