# .github/workflows/example.yml
name: 'Example workflow'

on:
  workflow_dispatch:
  
jobs:
  extract-rootfs:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v2
      - name: 'Extract rootfs'
        uses: ./
        with:
          image_name: 'ghcr.io/drunkod/coder-core:master'
          output_file: 'master-rootfs'
      - name: 'Upload artifact'
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.OUTPUT_FILE }}.tar.gz
          path: ${{ env.OUTPUT_FILE }}.tar.gz          
